name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: dschep/install-poetry-action@v1.2
    - name: Install requirements
      run: |
        poetry install
    - name: Lint
      run: |
        poetry run black -v --check .
    - name: Type check
      run: |
        poetry run mypy lmproof --ignore-missing-imports
